### ISSUE TITLE
add testcase for grab master wallet request payment flow

### ISSUE THREAD

**Issue by jacobshan** [StraitsX/Orchid-PBM#46]
do we have a testcase that checks whether a grab master wallet is able to request a payment successfully `on behalf of ` their user?

_Originally posted by @alcedo in https://github.com/StraitsX/Orchid-PBM/pull/45#discussion_r1646475615_

**Comment by alcedo** [comment]
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia2.giphy.com%2Fmedia%2Fl0HTYUmU67pLWv1a8%2Fgiphy.gif&token=nice" data-gitmeme-token="nice"><img src="https://media2.giphy.com/media/l0HTYUmU67pLWv1a8/giphy.gif" title="Created by gitme.me with /nice"
        alt="nice"/></a>
